### ISSUE TITLE
Some chars get garbled on paste

### ISSUE THREAD

**Issue by couzteau** [xavi-/node-copy-paste#21]
On Mac I see the following when using copy and paste in my own (unreleased) Brackets extension:
Copy `It’s nice to Meet you`
Paste results in `It‚Äôs nice to Meet you`

Copy `ström`

pastes as `str√∂m`

I also see the same chars garbled on win but the wrong result is slightly different, i.e. the `'` resolves to another funky char, example: `ItΓÇÖs nice to Meet you`

**Comment by metalkin** [comment]
On Windows, 'clip' takes utf16-le when you copy text. encode it to utf16-le and pass it to 'clip'.

var utf16le = new Buffer(text, 'utf16le');
child.stdin.end(utf16le);

**Comment by xavi-** [comment]
Sweet, thank you much.  I'll try to get that in by the end of the day.

**Comment by xavi-** [comment]
@metalkin thanks for the tip.  It seems to be working.  I'm still having trouble getting the encoding correct for paste though.  My guess is it's encoded in iso8859-1, but I haven't had a chance to test it out.

**Comment by xavi-** [comment]
Just pushed a release with windows encoding fixes (copy-paste@1.1.0).  Let me know if you're still seeing issues.
