### ISSUE TITLE
error:noeeror ;-)

### ISSUE THREAD

**Issue by brusand** [xavi-/node-copy-paste#22]
Hi Xavi,

i use your copy-paste module on w7 and for paste i have this issue :
[Error: no errorC:\DÃ©veloppements\nodejs\BrunoPhotosManager\node_modules\execSync\win32\v0.10\shell.node]

have you got an idea ?

(copy works well and install had no error)

here is my code
var cp = require('copy-paste').noConflict();
cp.copy('bruno', function() {
	console.log('copy done')
	cp.paste(function(txt) {console.log(txt)});
	
})

Best Regards
Bruno

**Comment by xavi-** [comment]
I was using a 3rd party `execSync` library.  My guess is that error was coming from there.  I've since upgraded `copy-paste` to use the native `execSync` if it's available.  Can you try using the latest version?

**Comment by xavi-** [comment]
Closed to inactivity.
