### ISSUE TITLE
Support in Windows 8.1

### ISSUE THREAD

**Issue by kuzzmi** [xavi-/node-copy-paste#25]
Sup guys.

Just tried to use that in Windows 8.1 x64 but without success.

Problem:
```javascript
λ node
> require("copy-paste").global()
{ copy: [Function],
  paste: [Function],
  silent: [Function],
  noConflict: [Function],
  global: [Function] }
> copy('asd')
'asd'
> paste()
'\r\n'
>
```

I've tried to dig around and found this [article](http://www.c3scripts.com/tutorials/msdos/paste.html). So if I try to use a library within a script file and override `require("copy-paste").paste` method to use the binary from article then everything works fine. Don't know whether that should be a "fallback". If so, let me know, I'll do a pull request.

Cheers,
Igor

**Comment by xavi-** [comment]
Yeah that'd make a great fallback.  A pull request would be much appreciated.

**Comment by xavi-** [comment]
Also what kind of errors were you getting with the VBscript?

**Comment by Otoris** [comment]
Think I'm getting a similar issue. VBscript looks to fail in Windows 8.1 x64.

```
C:\Users\Ethan\Dropbox\Sites symlink\share-clipboard-win>node share-clipboard.js

server started
child_process.js:1389
    throw err;
          ^
Error: Command failed: cscript /Nologo C:\Users\Ethan\Dropbox\Sites symlink\shar
e-clipboard-win\node_modules\copy-paste\platform.\fallbacks\paste.vbs

    at checkExecSyncError (child_process.js:1346:13)
    at Object.execSync (child_process.js:1386:13)
    at C:\Users\Ethan\Dropbox\Sites symlink\share-clipboard-win\node_modules\cop
y-paste\index.js:7:47
    at Object.exports.paste (C:\Users\Ethan\Dropbox\Sites symlink\share-clipboar
d-win\node_modules\copy-paste\index.js:75:51)
    at checkAndPushText (C:\Users\Ethan\Dropbox\Sites symlink\share-clipboard-wi
n\share-clipboard.js:18:33)
    at wrapper [as _onTimeout] (timers.js:265:14)
    at Timer.listOnTimeout (timers.js:110:15)
```

**Comment by xavi-** [comment]
Ahh, cool.  I'll implemented the fallback @kuzzmi recommended.

**Comment by xavi-** [comment]
I just published a new version that did path concat'ing a little different.  Would you mind updating and trying it out?

**Comment by Otoris** [comment]
Just reinstalled in a blank directory, appears to be the same issue.

!()[http://puu.sh/hZth0/8f82210730.png]

Executing the paste.vbs from explorer seems to work and pops up what's on my clipboard.

However if I directly execute the command in cmd, this is what I get. (after fixing the spacing in the path manually)

!()[http://puu.sh/hZtox/59140982bf.png]

I definitely have RAM and storage free.

**Comment by xavi-** [comment]
Thanks!  That was quick.

Hmm, I think it might be because "Sites symlink" path has a space in it.  I just published a new version (v1.1.2) that quoted the directory path.  Mind trying out this version as well?

**Comment by Otoris** [comment]
Boom! You fixed it. 

Thanks,

**Comment by xavi-** [comment]
:clap: :confetti_ball:
