### ISSUE TITLE
Remove execSync dependency

### ISSUE THREAD

**Issue by tomzx** [xavi-/node-copy-paste#26]
execSync is now deprecated.

As mentioned on [execSync](https://github.com/mgutz/execSync), both io.js and node.js now support the execSync function.

Please take the time to remove this package dependency to the execSync package.

See [node.js](http://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options) or [io.js](https://iojs.org/api/child_process.html#child_process_child_process_execsync_command_options) documentation.

Thanks!

**Comment by xavi-** [comment]
Probably won't remove execSync completely, because to maintain reverse compatibility.  But I will had a check for the native version.

**Comment by CMTegner** [comment]
> to maintain reverse compatibility

That's what major-increment releases are for ;)
