### ISSUE TITLE
Not working on linux

### ISSUE THREAD

**Issue by junaidcs** [xavi-/node-copy-paste#27]
Hi,
Thanks its working on Mac properly when i push it on server (linux), it does not work, give me this error.
[Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' .

I've installed Flash as well on server. Is there any other dependencies for this? 

Thanks.
Muhammad Junaid

**Comment by xavi-** [comment]
Hmm, can you check and see if `xclip` is installed on your linux server?  This module uses that command line utility to gain access to the system's clipboard.

**Comment by junaidcs** [comment]
I just installed with this command, but still not working
sudo apt-get install xclip. Any other solution you recommend ?

**Comment by xavi-** [comment]
What happens when you run this command?

```command
xclip -selection clipboard -o
```

**Comment by junaidcs** [comment]
It gives me this message
Error: Can't open display: (null)

**Comment by xavi-** [comment]
I think that means X isn't installed.

**Comment by xavi-** [comment]
Right now this modules depends on `xclip` and X being installed to work correctly, which is unfortunate, but I think of a robust alternative.  If you think of one, I'm all ears.

In the mean time, I'm going to close this issue.
