### ISSUE TITLE
Async paste() stops working in 1.1.2 under Win7

### ISSUE THREAD

**Issue by tepez** [xavi-/node-copy-paste#30]
I get the following error message when using paste async:
`CScript Error: Execution of the Windows Script Host failed. (Not enough storage is available to complete this operation. )`
Sync version works just fine. 

This happens in version `1.1.2`. Both sync and async works in `1.1.1`.

**Comment by tepez** [comment]
To clarify, the above error message is the `content` argument in the callback.
The error is just `null`.

**Comment by xavi-** [comment]
Thanks for the error report.  This should hopefully be fixed in v1.1.3 (002750075bbe9fcce19264db90dcc55e028909fa).
