### ISSUE TITLE
Switch from execSync dependency to sync-exec

### ISSUE THREAD

**Issue by jamiedust** [xavi-/node-copy-paste#33]
Hi, great package, but recently I have been having trouble.

execSync fails to compile on Node 0.12+ causing the install to fail. This dependency should be updated to sync-exec. See this execSync issue for reference: https://github.com/mgutz/execSync/issues/38

thanks!

**Comment by jmblog** [comment]
:+1:

**Comment by stuharvey** [comment]
I made a pull request which fixes this issue [here](https://github.com/xavi-/node-copy-paste/pull/35)

**Comment by xavi-** [comment]
Sorry about that.  Should be fixed in v1.1.4.
