### ISSUE TITLE
Is there any way to listen for clipboard changes?

### ISSUE THREAD

**Issue by HerrZatacke** [xavi-/node-copy-paste#36]
Hi,

I'd like my application to know when the content of the clipboard has changed.

I could imagine something like:
```javascript
var copypaste = require('copy-paste');
        
copypaste.listen(function(newData){
    console.log(newData);
});
```

is this something which might be implemented in the future?

**Comment by xavi-** [comment]
I'm not sure if that's possible.  The clipboard is completely controlled by the OS and as far as I know, there's no event bus of clipboard changes.
