### ISSUE TITLE
'copy' function does not handle 'undefined' text

### ISSUE THREAD

**Issue by tupini07** [xavi-/node-copy-paste#49]
Doing `var cp = require('copy-paste'); cp.copy(undefined);` throws an unhandled error.

I would expect 'copy-paste' to throw an error explaining that the text was undefined or that text should be treated as an empty string.

What should be done about this?

**Comment by xavi-** [comment]
Fixed in [`1.5.1`](https://www.npmjs.com/package/copy-paste/v/1.5.1)

Thanks for letting me know
