### ISSUE TITLE
copy-paste fails if you try to repeat the activity in a test

### ISSUE THREAD

**Issue by adrian-brown** [xavi-/node-copy-paste#51]
Say you have a test:

it('should copy to clipboard and paste){
myCopier.copy('this')
myCopier.paste()
//check paste was good
}

it('should copy to clipboard and paste second time){
myCopier.copy('that')
myCopier.paste()
//check paste was good
}

The first one is executed correctly, the second test has nothing in the clipboard.  Is there a way to flush it out, or is this a limitation?

**Comment by xavi-** [comment]
I believe the root issue is that `copy` is not synchronous.  I would recommend trying something like this:

```js
myCopier.copy('that', (err) => {
  if(err) throw err;
  myCopier.paste()
})
```
