### ISSUE TITLE
[window] support copy rtf format to clipboard

### ISSUE THREAD

**Issue by atian25** [xavi-/node-copy-paste#52]

**Comment by atian25** [comment]
ping @xavi-

**Comment by brightloudnoise** [comment]
I experimented with a copy fallback script in vbs, but it doesn't look like there is enough control over setting the clipboard value from that approach.  

So then I experimented with powershell scripts on Windows 10 and got the following working to a degree. It can take an -rtf 'withyourRTFstring' parameter. 

`Param(
    [string]$rtf='{\rtf1\ansi\deff0{\colortbl;\red0\green0\blue0;\red255\green0\blue0;}This!!! line is the default color\line\cf2This line is red\line\cf1This line is the default color}'
    )

# Load System.Windows.Forms assembly.
$null = [Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")

# Create data object.
$dataObject = New-Object windows.forms.dataobject

# Add generated strings to data object.
$dataObject.SetData([Windows.Forms.DataFormats]::Rtf, $true, $rtf)

# Put data object in system clipboard.
[Windows.Forms.Clipboard]::SetDataObject($dataObject, $true)
`

**Comment by atian25** [comment]
close due to not maintainer respone
