### ISSUE TITLE
Forward: Chinese encoding problem on Macbook ...

### ISSUE THREAD

**Issue by goessner** [xavi-/node-copy-paste#55]
While using your package in my VSCode extension there seems to be an issue copying Chinese language
on IOS (not on Windows 10).

Please have a look at [my issue](https://github.com/goessner/mdmath/issues/13)

thanks

**Comment by telesoho** [comment]
The extension use pbcopy and pdpaste command on IOS. You need to check pdpaste  work fine on your MacOSX Terminal.

你能看懂中文最好了，按照下面文章的设定貌似能解决这个问题：
http://blog.vgod.tw/2008/01/09/%E5%9C%A8macosx-terminal%E4%B8%AD%E4%BD%BF%E7%94%A8%E5%89%AA%E8%B2%BC%E7%B0%BF/

**Comment by xavi-** [comment]
This seems to happen when `LANG` environment variable is not set.  It should be fixed in [`1.5.2`](https://npmjs.com/package/copy-paste/v/1.5.2)
