### ISSUE TITLE
Doesn't work on default Debian install - as 'xclip' is not installed

### ISSUE THREAD

**Issue by richie5um** [xavi-/node-copy-paste#57]
Identified issue when had a bug reported against my project that uses this - https://github.com/richie5um/vscode-statusbar-json-path/issues/5

Easy to solve - by installing xclip - but there didn't seem to be an error reported back to my code that the command wasn't found.

**Comment by xavi-** [comment]
Errors are now more aggressively propagated in [`1.5.3`](https://www.npmjs.com/package/copy-paste/v/1.5.3)
