### ISSUE TITLE
win7 test case fail

### ISSUE THREAD

**Issue by frankLife** [xavi-/node-copy-paste#60]
It looks like something wrong.

![cp](https://user-images.githubusercontent.com/5081884/31513613-7334ba16-afc1-11e7-81b8-df71e238d40c.PNG)

It wil be much perfect if this problem would be fixed

**Comment by notatestuser** [comment]
Fixed in my fork: https://www.npmjs.com/package/copy-paste-win32fix

**Comment by frankLife** [comment]
@notatestuser It looks good. I appreciate your work on this and  I will try soon
