### ISSUE TITLE
Bug with copy and paste!

### ISSUE THREAD

**Issue by Denisov21** [xavi-/node-copy-paste#8]
Hi, 
I have a big problem:

1. Open Brackets
2. Copy any text editor (such as Microsoft Word, Notepad ...) the following characters ò à é è ° ù. (image 1)
3. In Brackets appear incorrectly (Image 2) Thank advantage
I have Brackets 37, Win 7, Keyboard Italian!

Image 1
![image 1](https://cloud.githubusercontent.com/assets/2547815/2687231/1d91217c-c243-11e3-9a87-0a87e7e6d494.JPG)

Image 2

![image 2](https://cloud.githubusercontent.com/assets/2547815/2687232/2a81e592-c243-11e3-8b30-b62a9679a975.JPG)

Thank advantage!

**Comment by xavi-** [comment]
Just pushed a release with windows encoding fixes (copy-paste@1.1.0).  Let me know if you're still seeing issues.
